### ISSUE TITLE
pypi package is missing files

### ISSUE THREAD

**Issue by JustTSK** [frontendr/python-rendertron#3]
Hello!

I tried to follow the installation guide but looks like pypi package is missing `decorators`, `middleware` and `storages` folders so the library is not working.

Here's the screenshot of what I have in virtualenv
<img width="480" alt="Screen Shot 2020-06-23 at 12 19 42 AM" src="https://user-images.githubusercontent.com/1076859/85372880-54b7d400-b4e7-11ea-9d80-632022d33f39.png">

And django is complaining too ```
ModuleNotFoundError: No module named 'rendertron.middleware
'```

**Comment by frontendr** [comment]
Hello @JustTSK,

Wow! Thanks for the report! I had no idea this was happening as I was only using my "local" code without ever using the code from pypi!

I've fixed the setup to include sub-packages so installing from pypi should work just fine now.

Regards!
