### ISSUE TITLE
default_settings is null.

### ISSUE THREAD

**Issue by yafeiaa** [frontendr/python-rendertron#4]
version: 0.2.1

<img width="677" alt="image" src="https://user-images.githubusercontent.com/50765823/157000518-fa7ece76-5e71-403d-a598-97391b2e187a.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/50765823/157000659-ffedab75-ab99-4a15-b633-ba7656edc564.png">
default_settings is null.

**Comment by frontendr** [comment]
I've not been able to reproduce this ticket. `default_settings` exists (see https://github.com/frontendr/python-rendertron/blob/develop/rendertron/default_settings.py).
